apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend
  labels:
    app: web
    type: front_end
spec:
  template:
    metadata:
      name: webserver
      labels:
        app: web
    spec:
      containers:
        - name: webserver
          image: nginx
  replicas: 2
  selector:
      matchLabels:
        app: web